const express = require('express');

const app = express();

app.get('/weather',(request,response)=>{   //你在执行时候就在搜索框输入：http://127.0.0.1:8000/weather
    response.setHeader('Access-Control-Allow-Origin','*');
    const data = {
        time:[
            {
                "cityid":"101120101",
                "city":"重庆",
                "update_time":"20:55",
                "wea":"晴",
                "wea_img":"yin",
                "tem":"11",
                "tem_day":"17°",
                "tem_night":"7°",
                "win":"东南风 ",
                "win_speed":"1级",
                "win_meter":"小于12km/h",
                "air":"73"
            },
            {
                "cityid":"101120101",
                "city":"重庆",
                "update_time":"20:55",
                "wea":"晴",
                "wea_img":"yin",
                "tem":"11",
                "tem_day":"18°",
                "tem_night":"6°",
                "win":"东南风 ",
                "win_speed":"1级",
                "win_meter":"小于12km/h",
                "air":"73"
            },
        ],
        hourly:[
            {
                "fixTime":"19:00",
                "temp": "18°",
                "text": "晴",
                "icon":"&#xe62b;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"20:00",
                "temp": "19°",
                "text": "晴",
                "icon":"&#xe61f;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"21:00",
                "temp": "19°",
                "text": "晴",
                "icon":"&#xe61f;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"22:00",
                "temp": "18°",
                "text": "晴",
                "icon":"&#xe61f;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"23:00",
                "temp": "20°",
                "text": "晴",
                "icon":"&#xe61f;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"00:00",
                "temp": "16°",
                "text": "晴",
                "icon":"&#xe61f;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"01:00",
                "temp": "16°",
                "text": "晴",
                "icon":"&#xe61f;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"02:00",
                "temp": "17°",
                "text": "晴",
                "icon":"&#xe61f;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"03:00",
                "temp": "18°",
                "text": "晴",
                "icon":"&#xe62b;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"04:00",
                "temp": "17°",
                "text": "晴",
                "icon":"&#xe62b;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"05:00",
                "temp": "18°",
                "text": "晴",
                "icon":"&#xe6c9;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"06:00",
                "temp": "18°",
                "text": "晴",
                "icon":"&#xe7ed;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"07:00",
                "temp": "19°",
                "text": "晴",
                "icon":"&#xe7ed;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
               
                "fixTime":"08:00",
                "temp": "20°",
                "text": "晴",
                "icon":"&#xe7ed;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                
                "fixTime":"09:00",
                "temp": "21°",
                "text": "晴",
                "icon":"&#xe7ed;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"10:00",
                "temp": "22°",
                "text": "晴",
                "icon":"&#xe7ed;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"11:00",
                "temp": "25°",
                "text": "晴",
                "icon":"&#xe7ed;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"12:00",
                "temp": "27°",
                "text": "晴",
                "icon":"&#xe7ed;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"13:00",
                "temp": "28°",
                "text": "晴",
                "icon":"&#xe7ed;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"14:00",
                "temp": "29°",
                "text": "晴",
                "icon":"&#xe7ed;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"15:00",
                "temp": "25°",
                "text": "晴",
                "icon":"&#xe7ed;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"16:00",
                "temp": "23°",
                "text": "晴",
                "icon":"&#xe7ed;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"17:00",
                "temp": "22°",
                "text": "晴",
                "icon":"&#xe7ed;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"18:00",
                "temp": "22°",
                "text": "晴",
                "icon":"&#xe6c8;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"19:00",
                "temp": "21°",
                "text": "晴",
                "icon":"&#xe62b;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
            {
                "fixTime":"20:00",
                "temp": "19°",
                "text": "晴",
                "icon":"&#xe62b;",
                "humidity": "11",
                "windDir": "西北风",
                "windScale": "4-5",
                "windSpeed": "25",
            },
        ],
        // 7日天气
        Sevdata:[
            {
                "week":"昨天",
                "date":"04/21",
                "wea_day":"晴",
                "wea_img_day":"&#xe61e;",
                "wea_img_night":"&#xe61e;",
                "tem_day":"30",
                "tem_night":"19",
                "wea_night":"多云",
                "win":"北风",
                "win_speed":"3级"
            },
            {
                "week":"今天",
                "date":"04/22",
                "wea_day":"晴",
                "wea_img_day":"&#xe61e;",
                "wea_img_night":"&#xe61e;",
                "tem_day":"27",
                "tem_night":"14",
                "wea_night":"多云",
                "win":"北风",
                "win_speed":"4级"
            },
            {
                "week":"明天",
                "date":"04/23",
                "wea_day":"晴",
                "wea_img_day":"&#xe61e;",
                "wea_img_night":"&#xe61e;",
                "tem_day":"31",
                "tem_night":"18",
                "wea_night":"多云",
                "win":"北风",
                "win_speed":"3级"
            },
            {
                "week":"周三",
                "date":"04/24",
                "wea_day":"晴",
                "wea_img_day":"&#xe61e;",
                "wea_img_night":"&#xe61e;",
                "tem_day":"33",
                "tem_night":"12",
                "wea_night":"多云",
                "win":"西南风",
                "win_speed":"5级"
            },
            {
                "week":"周四",
                "date":"04/25",
                "wea_day":"晴",
                "wea_img_day":"&#xe61e;",
                "wea_img_night":"&#xe61e;",
                "tem_day":"30",
                "tem_night":"13",
                "wea_night":"多云",
                "win":"东北风",
                "win_speed":"4级"
            },
            {
                "week":"周五",
                "date":"04/26",
                "wea_day":"多云",
                "wea_img_day":"&#xe61e;",
                "wea_img_night":"&#xe61e;",
                "tem_day":"29",
                "tem_night":"15",
                "wea_night":"多云",
                "win":"南风",
                "win_speed":"4级"
            },
            {
                "week":"周六",
                "date":"04/27",
                "wea_day":"晴",
                "wea_img_day":"&#xe61e;",
                "wea_img_night":"&#xe61e;",
                "tem_day":"29",
                "tem_night":"14",
                "wea_night":"多云",
                "win":"东风",
                "win_speed":"3级"
            },
            {
                "week":"周日",
                "date":"04/28",
                "wea_day":"晴",
                "wea_img_day":"&#xe61e;",
                "wea_img_night":"&#xe61e;",
                "tem_day":"28",
                "tem_night":"12",
                "wea_night":"多云",
                "win":"东南风",
                "win_speed":"3级"
            }
        ],
        life:[
            {
                "icon":"441;",
                "title":"穿衣",
                "sug":"热",
                "img":"&#xe68a;"
            },
            {
                "icon":"441;",
                "title":"雨伞",
                "sug":"不带伞",
                "img":"&#xe78a;",
            },
            {
                "icon":"441;",
                "title":"感冒",
                "sug":"少发",
                "img":"&#xe603;",
            },
            {
                "icon":"441;",
                "title":"洗车",
                "sug":"不宜",
                "img":"&#xe668;",
            },
            {
                "icon":"441;",
                "title":"运动",
                "sug":"适宜",
                "img":"&#xe6c2;",
            },
            {
                "icon":"441;",
                "title":"防晒",
                "sug":"中等",
                "img":"&#xe7ed;",
            },
            {
                "icon":"441;",
                "title":"钓鱼",
                "sug":"较适宜",
                "img":"&#xe604;",
            },
            {
                "icon":"441;",
                "title":"旅游",
                "sug":"适宜",
                "img":"&#xe756;",
            },
            {
                "icon":"441;",
                "title":"交通",
                "sug":"良好",
                "img":"&#xe600;",
            },
            {
                "icon":"441;",
                "title":"空气污染扩散条件",
                "sug":"中",
                "img":"&#xe61c;",
            },
            {
                "icon":"441;",
                "title":"舒适度",
                "sug":"舒适",
                "img":"&#xe75a;",
            },
            {
                "icon":"441;",
                "title":"中暑",
                "sug":"不会",
                "img":"&#xe767;",
            },
            {
                "icon":"441;",
                "title":"晾晒",
                "sug":"适宜",
                "img":"&#xe617;",
            },
            {
                "icon":"441;",
                "title":"化妆",
                "sug":"去油",
                "img":"&#xe614;",
            },
            {
                "icon":"441;",
                "title":"晨练",
                "sug":"适宜",
                "img":"&#xe807;",
            },
            {
                "icon":"441;",
                "title":"过敏",
                "sug":"过敏",
                "img":"&#xe632;",
            },
            {
                "icon":"441;",
                "title":"中暑",
                "sug":"无中暑风险",
                "img":"",
            }, 
           
               
        ]
        
    }
    let data1 = JSON.stringify(data)
    response.send(data1);
   
});

app.listen(8000,()=>{
    console.log("服务已经启动，8000 端口监听中……")
});
